GroupThink/GroupThink/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^admin/', include(admin.site.urls)),
]

GroupThink/wiki/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /wiki/5/
    url(r'^(?P<pk>[0-9]+)/$', views.ArticleView.as_view(), name='article'),
    # ex: /wiki/5/edit/
    url(r'^(?P<article_id>[0-9]+)/edit/$', views.EditView, name='edit'),
    # ex: /wiki/5/revisions/
    url(r'^(?P<article_id>[0-9]+)/revisions/$', views.RevisionsView, name='revisions'),
    # ex: /wiki/5/revert/2
    url(r'^(?P<article_id>[0-9]+)/revert/(?P<revision_id>[0-9]+)/$', views.RevertView, name='revert'),
]

GroupThink/wiki/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Text(models.Model):
	body = models.CharField(max_length=5000)
	
	def __str__(self):
		return self.body
		
	pass
	
class Revision(models.Model):
	text = models.ForeignKey(Text)
	date = models.DateTimeField('date modified')
	log = models.CharField(max_length=100)
	user = models.ForeignKey(User)
	
	def __str__(self):
		return self.date.strftime('%c')
		
	def was_recent_revision(self):
		return self.date >= timezone.now() - datetime.timedelta(days=1)
		
	pass
	

class Article(models.Model):
	title = models.CharField(max_length=50)
	date = models.DateTimeField('date created')
	latest = models.ForeignKey(Revision, related_name='+')
	creator = models.ForeignKey(User)
	revisions = models.ManyToManyField(Revision, related_name='Article')
	path = models.SlugField(max_length=40)
	
	def __str__(self):
		return self.title

GroupThink/wiki/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from .models import Article, Revision, Text

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		fields = ['title']
		
class RevisionForm(ModelForm):
	class Meta:
		model = Revision
		fields = ['log']
		
class TextForm(ModelForm):
	class Meta:
		model = Text
		fields = ['body']
		widgets = {
            'body': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

GroupThink/wiki/views.py
import datetime

from django.utils import timezone

from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic

from django.contrib.auth.models import User

from .models import Article, Revision, Text
from .forms import ArticleForm, RevisionForm, TextForm
    
class IndexView(generic.ListView):
    template_name = 'pages/index.html'
    context_object_name = 'articles_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by('-date')[:5]

class ArticleView(generic.DetailView):
    model = Article
    template_name = 'pages/article.html'
     
def EditView(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
        
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        article_form = ArticleForm(request.POST)
        revision_form = RevisionForm(request.POST)
        text_form = TextForm(request.POST)
        
        # check whether it's valid:
        if revision_form.is_valid() and text_form.is_valid():
        
            # Creates a new text object with the form input
            text = Text(body=text_form.cleaned_data['body'])
            text.save()
            
            #TODO: correctly access user
            user = User.objects.get(id=1)
            
            # Creates a new revision with the updated text
            revision = Revision(text=text, date=timezone.now(), log=revision_form.cleaned_data['log'], user=user)
            revision.save()
        
            article.latest = revision
            article.revisions.add(revision)
            article.save()
            
            # process the data in form.cleaned_data as required
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('wiki:article', args=(article.id,)))
        else:
            return render(request, 'pages/article.html', {'article': article})

    # if a GET (or any other method) we'll create a blank form
    else:
        article_form = ArticleForm(instance=article)
        revision_form = RevisionForm()
        text_form = TextForm(instance=article.latest.text)
        
        return render(request, 'pages/edit.html', 
        {'article': article,
         'article_form': article_form,
         'revision_form': revision_form,
         'text_form': text_form,
         })

def RevisionsView(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'pages/revisions.html', {'article': article})
    
def RevertView(request, article_id, revision_id):
    article = get_object_or_404(Article, pk=article_id)
    revision = get_object_or_404(Revision, pk=revision_id)
    
    if article.latest.text == revision.text:
        # TODO: Display an error
        error_message = 'Target revision identical to current'
        
        return HttpResponseRedirect(reverse('wiki:revisions', args=(article.id,)))
    
    else:
        # Default log message for reversion
        log_message = 'Reverted to ' + revision.date.strftime('%c')
    
        user = User.objects.get(id=1)
        user.save()
    
        new_revision = Revision(text=revision.text, date=timezone.now(), log=log_message, user=user)
        new_revision.save()
        
        article.latest = new_revision
        article.save()
        article.revisions.add(new_revision)
    
        return HttpResponseRedirect(reverse('wiki:revisions', args=(article.id,)))

GroupThink/wiki/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% block title %}
    {% endblock %}

    {% include "utility/stylesheets.html" %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block heading %}
    {% endblock %}
    
    {%  block tabs %}
    {% endblock %}
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    {% block content %}
    {% endblock %}

    {% include "utility/scripts.html" %}
  </body>
</html>

GroupThink/wiki/templates/blocks/tabs.html
<ul class="nav nav-tabs">
  <li role="utility"><a href="{% url 'wiki:article' article.id %}">Article</a></li>
  <li role="utility"><a href="{% url 'wiki:edit' article.id %}">Edit</a></li>
  <li role="utility"><a href="{% url 'wiki:revisions' article.id %}">Revisions</a></li>
</ul>

GroupThink/wiki/templates/pages/article.html
{% extends "base.html" %}

{% block title %}
<title>{{ article.title }}</title>
{% endblock %}

{% block heading %}
<h1>{{ article.title }}</h1>
{% endblock %}

{% block tabs %}
{% include "blocks/tabs.html" %}
{% endblock %}

{% block content %}
<p>{{ article.latest.text.body }}</p>
<p><strong>{{ article.latest.date }}</strong></p>
{% endblock %}

GroupThink/wiki/templates/pages/edit.html
{% extends "base.html" %}

{% block title %}
<title>Edit: {{ article.title }}</title>
{% endblock %}

{% block heading %}
<h1>Edit: {{ article.title }}</h1>
{% endblock %}

{% block tabs %}
{% include "blocks/tabs.html" %}
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div id="text-body">{{ text_form }}</div>
    <div id="revision-info">{{ revision_form }}</div>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

GroupThink/wiki/templates/pages/index.html
{% extends "base.html" %}

{% block title %}
<title>Index</title>
{% endblock %}

{% block heading %}
<h1>Index</h1>
{% endblock %}

{% block content %}
<ul>
{% for article in articles_list %}
    <li>{{ article.title }} -- {{ article.date }} -- {{ article.creator }}
    </li>
{% endfor %}
</ul>
{% endblock %}

GroupThink/wiki/templates/pages/revisions.html
{% extends "base.html" %}

{% block title %}
<title>Revisions: {{ article.title }}</title>
{% endblock %}

{% block heading %}
<h1>Revisions: {{ article.title }}</h1>
{% endblock %}

{% block tabs %}
{% include "blocks/tabs.html" %}
{% endblock %}

{% block content %}
<ul>
{% for revision in article.revisions.all %}
    <li>{{ revision.date }} -- {{ revision.user }} -- {{ revision.log }} --
        <a href="{% url 'wiki:revert' article_id=article.id revision_id=revision.id %}">Revert</a>
    </li>
{% endfor %}
</ul>
{% endblock %}

GroupThink/wiki/templates/utility/scripts.html
{% load staticfiles %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

GroupThink/wiki/templates/utility/stylesheets.html
{% load staticfiles %}
<!-- Bootstrap -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">